project:
  type: website

website:
  title: "Simple Brand Example"
  navbar:
    title: "rOpenSpain"
    tools:
    - icon: home
      href: https://ropenspain.es
    - icon: github
      href: https://github.com/rOpenSpain/

  favicon: ./assets/favicon.png
  page-footer:
    left: "This is a test footer"
    right: >
      Visit <a href="https://posit-dev.github.io/brand-yml/">brand-yml</a> for
      more info.

format:
  html:
    css: styles.css

highlight-style: tango

editor: visual
